export  const GET_ALL_MOVIES = 'GET_ALL_MOVIES'
export  const GET_ERROR = 'GET_ERROR'
export  const GET_ONE_MOVIE = 'GET_ONE_MOVIE'
export  const UPDATE_MOVIE = 'UPDATE_MOVIE'
export  const DELETE_MOVIE = 'DELETE_MOVIE'
export  const FETCH_DATA = 'FETCH_DATA'